import 'dotenv/config';
import mongoose from 'mongoose';
import Investor from '../modules/investors/investor.model.js';

const MONGODB_URI = process.env.MONGODB_URI;
if (!MONGODB_URI) {
  console.error('MONGODB_URI environment variable is required');
  process.exit(1);
}

export const DEMO_INVESTORS = [
  {
    name: 'Sarah Chen',
    organization: 'Horizon Ventures',
    investorType: 'vc',
    thesis: 'We back early-stage founders building transformative fintech and saas products for emerging markets. We look for strong technical teams with a clear go-to-market strategy.',
    industries: ['fintech', 'saas'],
    stages: ['pre-seed', 'seed'],
    geographies: ['Southeast Asia', 'Africa', 'Latin America'],
    minTicketSize: 100000,
    maxTicketSize: 500000,
    preferredBusinessModels: ['b2b', 'saas'],
    websiteUrl: 'https://horizonventures.example.com',
    isDemoData: true,
    isActive: true,
    sourceType: 'demo',
  },
  {
    name: 'Marcus Williams',
    organization: 'Nexus Capital Partners',
    investorType: 'vc',
    thesis: 'Focused on Series A and B companies in healthtech and biotech. We bring deep operational experience and a global network to help founders scale.',
    industries: ['healthtech', 'biotech'],
    stages: ['series-a', 'series-b'],
    geographies: ['United States', 'United Kingdom', 'Germany'],
    minTicketSize: 2000000,
    maxTicketSize: 10000000,
    preferredBusinessModels: ['b2b', 'b2b2c'],
    websiteUrl: 'https://nexuscapital.example.com',
    isDemoData: true,
    isActive: true,
    sourceType: 'demo',
  },
  {
    name: 'Priya Nair',
    organization: 'Aurora Growth Fund',
    investorType: 'vc',
    thesis: 'We invest in mission-driven edtech and hrtech startups that are reimagining how people learn and work. Strong preference for product-led growth companies.',
    industries: ['edtech', 'hrtech'],
    stages: ['seed', 'series-a'],
    geographies: ['India', 'United States', 'Singapore'],
    minTicketSize: 500000,
    maxTicketSize: 3000000,
    preferredBusinessModels: ['saas', 'marketplace'],
    websiteUrl: 'https://auroragrowth.example.com',
    isDemoData: true,
    isActive: true,
    sourceType: 'demo',
  },
  {
    name: 'James Okafor',
    organization: 'Pinnacle Angel Network',
    investorType: 'angel',
    thesis: 'Angel investor focused on pre-seed ecommerce and marketplace businesses in Sub-Saharan Africa. I look for founders with deep local market knowledge.',
    industries: ['ecommerce', 'marketplace', 'logistics'],
    stages: ['pre-seed'],
    geographies: ['Nigeria', 'Kenya', 'Ghana'],
    minTicketSize: 25000,
    maxTicketSize: 150000,
    preferredBusinessModels: ['b2c', 'marketplace'],
    websiteUrl: 'https://pinnacleangels.example.com',
    isDemoData: true,
    isActive: true,
    sourceType: 'demo',
  },
  {
    name: 'Elena Sorokina',
    organization: 'Deepwater Tech Fund',
    investorType: 'vc',
    thesis: 'Investing in deeptech and cleantech companies solving climate and sustainability challenges. We are patient capital with a 10-year horizon.',
    industries: ['deeptech', 'cleantech'],
    stages: ['seed', 'series-a', 'series-b'],
    geographies: ['Europe', 'North America', 'Israel'],
    minTicketSize: 1000000,
    maxTicketSize: 8000000,
    preferredBusinessModels: ['b2b', 'deeptech'],
    websiteUrl: 'https://deepwatertech.example.com',
    isDemoData: true,
    isActive: true,
    sourceType: 'demo',
  },
  {
    name: 'Hiroshi Tanaka',
    organization: 'Sakura Ventures',
    investorType: 'vc',
    thesis: 'Backing Japanese and pan-Asian SaaS companies expanding globally. We help founders navigate the complexities of international go-to-market.',
    industries: ['saas', 'enterprise'],
    stages: ['series-a', 'series-b'],
    geographies: ['Japan', 'South Korea', 'Taiwan', 'Singapore'],
    minTicketSize: 1500000,
    maxTicketSize: 7000000,
    preferredBusinessModels: ['saas', 'b2b'],
    websiteUrl: 'https://sakuraventures.example.com',
    isDemoData: true,
    isActive: true,
    sourceType: 'demo',
  },
  {
    name: 'Amara Diallo',
    organization: 'Meridian Impact Capital',
    investorType: 'vc',
    thesis: 'Impact-first investor focused on legaltech and proptech solutions that increase access for underserved communities. We measure returns in both financial and social terms.',
    industries: ['legaltech', 'proptech'],
    stages: ['pre-seed', 'seed'],
    geographies: ['West Africa', 'East Africa', 'South Africa'],
    minTicketSize: 50000,
    maxTicketSize: 500000,
    preferredBusinessModels: ['b2c', 'b2b2c'],
    websiteUrl: 'https://meridianimpact.example.com',
    isDemoData: true,
    isActive: true,
    sourceType: 'demo',
  },
  {
    name: 'Richard Bowman',
    organization: 'Apex Family Office',
    investorType: 'family-office',
    thesis: 'We are a multi-generational family office investing in growth-stage consumer and media businesses with proven unit economics.',
    industries: ['consumer', 'media'],
    stages: ['series-b', 'series-c', 'growth'],
    geographies: ['United States', 'Canada', 'United Kingdom'],
    minTicketSize: 5000000,
    maxTicketSize: 25000000,
    preferredBusinessModels: ['b2c', 'marketplace'],
    websiteUrl: 'https://apexfamilyoffice.example.com',
    isDemoData: true,
    isActive: true,
    sourceType: 'demo',
  },
  {
    name: 'Fatima Al-Rashid',
    organization: 'Crescent Technology Ventures',
    investorType: 'vc',
    thesis: 'Investing in fintech and ecommerce startups across MENA and Turkey. We bring regional expertise and government partnerships to accelerate growth.',
    industries: ['fintech', 'ecommerce'],
    stages: ['seed', 'series-a'],
    geographies: ['UAE', 'Saudi Arabia', 'Egypt', 'Turkey'],
    minTicketSize: 300000,
    maxTicketSize: 2000000,
    preferredBusinessModels: ['b2b2c', 'marketplace'],
    websiteUrl: 'https://crescenttech.example.com',
    isDemoData: true,
    isActive: true,
    sourceType: 'demo',
  },
  {
    name: 'David Park',
    organization: 'Catalyst Accelerator',
    investorType: 'accelerator',
    thesis: 'We run a 12-week accelerator for pre-seed startups in any industry. $150K for 7% equity. We focus on helping founders find product-market fit quickly.',
    industries: ['saas', 'fintech', 'healthtech', 'edtech'],
    stages: ['pre-seed'],
    geographies: ['United States', 'Canada'],
    minTicketSize: 150000,
    maxTicketSize: 150000,
    preferredBusinessModels: ['saas', 'b2b', 'b2c'],
    websiteUrl: 'https://catalystaccelerator.example.com',
    isDemoData: true,
    isActive: true,
    sourceType: 'demo',
  },
  {
    name: 'Luisa Ferreira',
    organization: 'Verde Capital',
    investorType: 'vc',
    thesis: 'Cleantech and biotech investor focused on the Brazilian and broader Latin American market. We support founders building climate solutions tailored to the Global South.',
    industries: ['cleantech', 'biotech'],
    stages: ['seed', 'series-a'],
    geographies: ['Brazil', 'Colombia', 'Chile', 'Mexico'],
    minTicketSize: 500000,
    maxTicketSize: 4000000,
    preferredBusinessModels: ['b2b', 'deeptech'],
    websiteUrl: 'https://verdecapital.example.com',
    isDemoData: true,
    isActive: true,
    sourceType: 'demo',
  },
  {
    name: 'Alexander Petrov',
    organization: 'Baltic Tech Investors',
    investorType: 'vc',
    thesis: 'Early-stage investor in enterprise SaaS and deeptech from the Nordics and Baltic states expanding to global markets.',
    industries: ['saas', 'enterprise', 'deeptech'],
    stages: ['pre-seed', 'seed'],
    geographies: ['Estonia', 'Latvia', 'Lithuania', 'Finland', 'Sweden'],
    minTicketSize: 200000,
    maxTicketSize: 1500000,
    preferredBusinessModels: ['saas', 'b2b'],
    websiteUrl: 'https://baltictechinvestors.example.com',
    isDemoData: true,
    isActive: true,
    sourceType: 'demo',
  },
  {
    name: 'Nkechi Okonkwo',
    organization: 'Trailblazer Growth Partners',
    investorType: 'vc',
    thesis: 'We back high-growth logistics and proptech companies transforming infrastructure in emerging markets. We are hands-on investors who co-build with founders.',
    industries: ['logistics', 'proptech'],
    stages: ['series-a', 'series-b'],
    geographies: ['Nigeria', 'South Africa', 'Egypt', 'Kenya'],
    minTicketSize: 1000000,
    maxTicketSize: 6000000,
    preferredBusinessModels: ['marketplace', 'b2b'],
    websiteUrl: 'https://trailblazergrowth.example.com',
    isDemoData: true,
    isActive: true,
    sourceType: 'demo',
  },
  {
    name: 'Thomas Müller',
    organization: 'Rhine Valley Ventures',
    investorType: 'vc',
    thesis: 'German-speaking European investor focused on B2B SaaS and enterprise software replacing legacy systems in manufacturing and supply chain.',
    industries: ['saas', 'enterprise'],
    stages: ['series-a', 'series-b'],
    geographies: ['Germany', 'Austria', 'Switzerland'],
    minTicketSize: 2000000,
    maxTicketSize: 12000000,
    preferredBusinessModels: ['saas', 'b2b'],
    websiteUrl: 'https://rhinevalleyventures.example.com',
    isDemoData: true,
    isActive: true,
    sourceType: 'demo',
  },
  {
    name: 'Sophie Laurent',
    organization: 'Lumière Capital',
    investorType: 'vc',
    thesis: 'We invest in French and pan-European consumer and media startups at Series A. We love brands with strong cultural identity and omnichannel strategies.',
    industries: ['consumer', 'media', 'ecommerce'],
    stages: ['series-a'],
    geographies: ['France', 'Belgium', 'Spain', 'Italy'],
    minTicketSize: 1500000,
    maxTicketSize: 8000000,
    preferredBusinessModels: ['b2c', 'marketplace'],
    websiteUrl: 'https://lumierecapital.example.com',
    isDemoData: true,
    isActive: true,
    sourceType: 'demo',
  },
  {
    name: 'Kwame Asante',
    organization: 'Volta Ventures Africa',
    investorType: 'vc',
    thesis: 'Investing in seed-stage fintech and healthtech companies building financial and healthcare access for the underbanked in West Africa.',
    industries: ['fintech', 'healthtech'],
    stages: ['pre-seed', 'seed'],
    geographies: ['Ghana', 'Ivory Coast', 'Senegal', 'Nigeria'],
    minTicketSize: 100000,
    maxTicketSize: 750000,
    preferredBusinessModels: ['b2c', 'b2b2c'],
    websiteUrl: 'https://voltaventuresafrica.example.com',
    isDemoData: true,
    isActive: true,
    sourceType: 'demo',
  },
  {
    name: 'Irina Kovacs',
    organization: 'Danube Digital Fund',
    investorType: 'vc',
    thesis: 'Supporting Central and Eastern European founders in gaming, media, and consumer tech to scale their products internationally.',
    industries: ['gaming', 'media', 'consumer'],
    stages: ['seed', 'series-a'],
    geographies: ['Poland', 'Czech Republic', 'Hungary', 'Romania'],
    minTicketSize: 300000,
    maxTicketSize: 2500000,
    preferredBusinessModels: ['b2c', 'marketplace'],
    websiteUrl: 'https://danubedigital.example.com',
    isDemoData: true,
    isActive: true,
    sourceType: 'demo',
  },
  {
    name: 'Carlos Vega',
    organization: 'Andean Tech Capital',
    investorType: 'vc',
    thesis: 'Early-stage investor in SaaS and marketplace businesses in the Andean region. We specialize in helping founders navigate regulatory and payment infrastructure challenges.',
    industries: ['saas', 'marketplace', 'fintech'],
    stages: ['pre-seed', 'seed'],
    geographies: ['Peru', 'Ecuador', 'Bolivia', 'Colombia'],
    minTicketSize: 75000,
    maxTicketSize: 600000,
    preferredBusinessModels: ['saas', 'marketplace'],
    websiteUrl: 'https://andeantech.example.com',
    isDemoData: true,
    isActive: true,
    sourceType: 'demo',
  },
  {
    name: 'Mei Lin',
    organization: 'Pacific Rim Innovations',
    investorType: 'corporate-vc',
    thesis: 'The corporate venture arm of a large Asia-Pacific conglomerate. We invest in deep tech and logistics startups that can integrate with or sell to our portfolio companies.',
    industries: ['deeptech', 'logistics', 'enterprise'],
    stages: ['series-a', 'series-b', 'series-c'],
    geographies: ['China', 'Hong Kong', 'Vietnam', 'Thailand'],
    minTicketSize: 3000000,
    maxTicketSize: 20000000,
    preferredBusinessModels: ['b2b', 'deeptech'],
    websiteUrl: 'https://pacificriminnovations.example.com',
    isDemoData: true,
    isActive: true,
    sourceType: 'demo',
  },
  {
    name: 'Olu Adeyemi',
    organization: 'Sunrise Seed Fund',
    investorType: 'angel',
    thesis: 'Former fintech founder turned angel investor. I write small checks into pre-seed fintech and legaltech companies across Anglophone Africa.',
    industries: ['fintech', 'legaltech'],
    stages: ['pre-seed'],
    geographies: ['Nigeria', 'South Africa', 'Zimbabwe', 'Zambia'],
    minTicketSize: 10000,
    maxTicketSize: 75000,
    preferredBusinessModels: ['b2b', 'b2c'],
    websiteUrl: 'https://sunriseseedfund.example.com',
    isDemoData: true,
    isActive: true,
    sourceType: 'demo',
  },
  {
    name: 'Anastasia Volkov',
    organization: 'Northern Lights Capital',
    investorType: 'vc',
    thesis: 'We invest in cleantech and deeptech out of Scandinavia and the Nordics. Our portfolio companies benefit from our access to European public funding and grants.',
    industries: ['cleantech', 'deeptech'],
    stages: ['seed', 'series-a', 'series-b'],
    geographies: ['Norway', 'Sweden', 'Denmark', 'Finland'],
    minTicketSize: 800000,
    maxTicketSize: 5000000,
    preferredBusinessModels: ['b2b', 'deeptech'],
    websiteUrl: 'https://northernlightscapital.example.com',
    isDemoData: true,
    isActive: true,
    sourceType: 'demo',
  },
  {
    name: 'Benjamin Osei',
    organization: 'Rooftop Ventures',
    investorType: 'vc',
    thesis: 'We back proptech and hrtech founders reinventing how people work and live in the 21st century. We focus on companies with strong network effects.',
    industries: ['proptech', 'hrtech'],
    stages: ['seed', 'series-a'],
    geographies: ['United States', 'United Kingdom', 'Australia'],
    minTicketSize: 500000,
    maxTicketSize: 3000000,
    preferredBusinessModels: ['saas', 'marketplace'],
    websiteUrl: 'https://rooftopventures.example.com',
    isDemoData: true,
    isActive: true,
    sourceType: 'demo',
  },
  {
    name: 'Valentina Cruz',
    organization: 'Selva Impact Fund',
    investorType: 'vc',
    thesis: 'Impact investor focusing on edtech and healthtech companies improving outcomes for rural and indigenous communities in Latin America.',
    industries: ['edtech', 'healthtech'],
    stages: ['pre-seed', 'seed'],
    geographies: ['Mexico', 'Guatemala', 'Peru', 'Bolivia'],
    minTicketSize: 50000,
    maxTicketSize: 400000,
    preferredBusinessModels: ['b2c', 'b2b2c'],
    websiteUrl: 'https://selvaimpact.example.com',
    isDemoData: true,
    isActive: true,
    sourceType: 'demo',
  },
  {
    name: 'Patrick Hoffmann',
    organization: 'Schwarzwald Capital',
    investorType: 'family-office',
    thesis: 'A European family office with a 50-year heritage investing in manufacturing and industrial deeptech companies that are transitioning to Industry 4.0.',
    industries: ['deeptech', 'enterprise'],
    stages: ['series-b', 'series-c', 'growth'],
    geographies: ['Germany', 'France', 'Netherlands', 'Belgium'],
    minTicketSize: 10000000,
    maxTicketSize: 50000000,
    preferredBusinessModels: ['b2b', 'deeptech'],
    websiteUrl: 'https://schwarzwaldcapital.example.com',
    isDemoData: true,
    isActive: true,
    sourceType: 'demo',
  },
  {
    name: 'Yuki Nakamura',
    organization: 'Shinkansen Ventures',
    investorType: 'vc',
    thesis: 'We invest in gaming and media technology companies that are building the infrastructure for next-generation interactive entertainment.',
    industries: ['gaming', 'media', 'deeptech'],
    stages: ['seed', 'series-a'],
    geographies: ['Japan', 'South Korea', 'United States'],
    minTicketSize: 500000,
    maxTicketSize: 4000000,
    preferredBusinessModels: ['b2c', 'marketplace'],
    websiteUrl: 'https://shinkansenvntures.example.com',
    isDemoData: true,
    isActive: true,
    sourceType: 'demo',
  },
  {
    name: 'Adaeze Eze',
    organization: 'Greenfield Accelerator Africa',
    investorType: 'accelerator',
    thesis: 'A Nairobi-based accelerator providing $50K pre-seed funding plus a structured 10-week program for early-stage African startups across all sectors.',
    industries: ['fintech', 'healthtech', 'ecommerce', 'logistics'],
    stages: ['pre-seed'],
    geographies: ['Kenya', 'Tanzania', 'Uganda', 'Rwanda'],
    minTicketSize: 50000,
    maxTicketSize: 50000,
    preferredBusinessModels: ['b2b', 'b2c', 'marketplace'],
    websiteUrl: 'https://greenfieldafrica.example.com',
    isDemoData: true,
    isActive: true,
    sourceType: 'demo',
  },
  {
    name: 'Marco Esposito',
    organization: 'Colosseum Digital Partners',
    investorType: 'vc',
    thesis: 'Southern European investor backing ambitious founders in fintech, ecommerce, and marketplace at Series A. We have deep connections to traditional industries ripe for disruption.',
    industries: ['fintech', 'ecommerce', 'marketplace'],
    stages: ['series-a'],
    geographies: ['Italy', 'Greece', 'Portugal', 'Spain'],
    minTicketSize: 1000000,
    maxTicketSize: 6000000,
    preferredBusinessModels: ['b2b2c', 'marketplace'],
    websiteUrl: 'https://colosseumdigital.example.com',
    isDemoData: true,
    isActive: true,
    sourceType: 'demo',
  },
  {
    name: 'Chloe Bergmann',
    organization: 'Zenith Health Ventures',
    investorType: 'vc',
    thesis: 'Exclusively focused on Series A and B digital health companies. We have a team of clinical advisors who help evaluate and accelerate portfolio companies.',
    industries: ['healthtech', 'biotech'],
    stages: ['series-a', 'series-b'],
    geographies: ['United States', 'Israel', 'United Kingdom'],
    minTicketSize: 3000000,
    maxTicketSize: 15000000,
    preferredBusinessModels: ['b2b', 'b2b2c'],
    websiteUrl: 'https://zenithhealth.example.com',
    isDemoData: true,
    isActive: true,
    sourceType: 'demo',
  },
  {
    name: 'Omar Al-Faisal',
    organization: 'Desert Rose Capital',
    investorType: 'vc',
    thesis: 'Backing MENA founders building B2B SaaS and enterprise solutions to modernize government services and large corporates in the Gulf region.',
    industries: ['saas', 'enterprise', 'legaltech'],
    stages: ['seed', 'series-a'],
    geographies: ['Saudi Arabia', 'UAE', 'Kuwait', 'Bahrain'],
    minTicketSize: 500000,
    maxTicketSize: 4000000,
    preferredBusinessModels: ['saas', 'b2b'],
    websiteUrl: 'https://desertrosecapital.example.com',
    isDemoData: true,
    isActive: true,
    sourceType: 'demo',
  },
  {
    name: 'Grace Kimani',
    organization: 'Savanna Ventures',
    investorType: 'vc',
    thesis: 'East African VC investing in agritech and logistics startups that strengthen food systems and supply chains across the continent.',
    industries: ['logistics', 'ecommerce'],
    stages: ['pre-seed', 'seed', 'series-a'],
    geographies: ['Kenya', 'Ethiopia', 'Tanzania', 'Uganda'],
    minTicketSize: 100000,
    maxTicketSize: 1000000,
    preferredBusinessModels: ['marketplace', 'b2b'],
    websiteUrl: 'https://savannaventures.example.com',
    isDemoData: true,
    isActive: true,
    sourceType: 'demo',
  },
];

async function seed() {
  try {
    await mongoose.connect(MONGODB_URI, { serverSelectionTimeoutMS: 5000 });
    console.log('Connected to MongoDB');

    let upserted = 0;
    let modified = 0;

    for (let i = 0; i < DEMO_INVESTORS.length; i++) {
      const investor = DEMO_INVESTORS[i];
      const result = await Investor.findOneAndUpdate(
        { name: investor.name, organization: investor.organization },
        { $set: investor },
        { upsert: true, new: true },
      );

      if (result) {
        upserted++;
      } else {
        modified++;
      }

      if ((i + 1) % 10 === 0) {
        console.log(`Progress: ${i + 1}/${DEMO_INVESTORS.length} investors processed`);
      }
    }

    console.log(`Seed complete. ${DEMO_INVESTORS.length} demo investors upserted.`);

    const total = await Investor.countDocuments({ isDemoData: true });
    console.log(`Total demo investors in database: ${total}`);
  } catch (err) {
    console.error('Seed failed:', err.message);
    process.exit(1);
  } finally {
    await mongoose.disconnect();
    console.log('Database disconnected');
  }
}

seed();
